version: '3.8'

services:
  musika-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: musika-app
    ports:
      - "8888:8888"
    # volumes:
      # - "./notebooks:/usr/src/app/musika"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]