# Use an official TensorFlow runtime as a parent image, with GPU support
FROM tensorflow/tensorflow:2.10.0-gpu-jupyter

# Set the working directory in the container
WORKDIR /usr/src/app

# Install git and ffmpeg
RUN apt-get update && \
    apt-get install -y git ffmpeg && \
    rm -rf /var/lib/apt/lists/*

# Clone the specified GitHub repository
# RUN git clone https://github.com/marcoppasini/musika.git

# Change the working directory to the cloned repository
WORKDIR /usr/src/app/musika

# Copy the requirements text into the container
COPY requirements_1.txt ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements_1.txt

# If necessary, update typing_extensions to a version that includes 'deprecated'
RUN pip install --no-cache-dir --upgrade typing_extensions

EXPOSE 8888 7860

# Adding a user to prevent permission problem later and inconsistency
# src: https://vsupalov.com/docker-shared-permissions/
RUN useradd -m -d /tf user && \
     chown -R user /tf && \
     adduser user sudo && \
     echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER user